const adventCalendar = [
    "Chocolate",
    "Candy cane",
    "Small toy",
    "Puzzle",
    "Christmas ornament",
    "Holiday socks",
    "DIY holiday card",
    "Hot cocoa mix",
    "Festive stickers",
    "Miniature figurine",
    "Holiday-themed bookmark",
    "Cookie cutter",
    "Mini scented candle",
    "Christmas-themed erasers",
    "DIY snow globe kit",
    "Festive keychain",
    "Winter-themed temporary tattoos",
    "Mini jigsaw puzzle",
    "Holiday-themed magnet",
    "Personalized ornament",
    "Christmas-themed cookie",
    "Small plush toy",
    "DIY paper snowflakes",
    "Christmas Eve surprise"
];
